from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"
VERSION_HISTORY = ROOT / "VERSION_HISTORY.md"
OUTPUT = ROOT / "GREASYFORK_ADDITIONAL_INFO.md"


def main() -> None:
    readme = README.read_text(encoding="utf-8").strip()
    version_history = VERSION_HISTORY.read_text(encoding="utf-8").strip()

    content = f"""# Minerva (Greasy Fork Additional Info)

This file is auto-generated from `README.md` and `VERSION_HISTORY.md`.
Do not edit this file directly. Update the source files instead.

---

{readme}

---

{version_history}
"""
    OUTPUT.write_text(content.rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT.name}")


if __name__ == "__main__":
    main()
